### ISSUE TITLE
Unable to load DLL 'libglib-2.0-0.dll'

### ISSUE THREAD

**Issue by ilya-fiveisky** [zenprotocol/zen-wallet#7]
When I try to start Zen wallet (on Windows 8.1) I get in console the following text with error
> 
>  ***** Node starting with args:
> 
> BlockChain(I) No tip.
> Network(I) Magic is 1
> Network(I) Warning, found 2 internal addresses
> Network(W) Remaining peers to get : 10
> System.DllNotFoundException: Unable to load DLL 'libglib-2.0-0.dll': The specifi
> ed module could not be found. (Exception from HRESULT: 0x8007007E)
>    at GLib.Marshaller.g_malloc(UIntPtr size)
>    at GLib.Marshaller.StringToPtrGStrdup(String str)
>    at GLib.Global.set_ProgramName(String value)
>    at Gtk.Application.SetPrgname()
>    at Gtk.Application.Init()
>    at Wallet.App.Start(WalletManager walletManager, NodeManager nodeManager)
>    at Zen.App.GUI(Boolean shutdownOnClose)
>    at Zen.Program.Main(String[] args)
> 
> Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libglib-2.
> 0-0.dll': The specified module could not be found. (Exception from HRESULT: 0x80
> 07007E)
>    at GLib.Marshaller.g_malloc(UIntPtr size)
>    at GLib.Marshaller.StringToPtrGStrdup(String str)
>    at GLib.Global.set_ProgramName(String value)
>    at Gtk.Application.SetPrgname()
>    at Gtk.Application.Init()
>    at Wallet.App.Start(WalletManager walletManager, NodeManager nodeManager)
>    at Zen.App.GUI(Boolean shutdownOnClose)
>    at Zen.Program.Main(String[] args)
>

**Comment by ilya-fiveisky** [comment]
Workaround - install  [Gtk#](https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.45.msi)

**Comment by dreadlokeur** [comment]
Same error on Windows 7 with Gtk# installed

**Comment by Cremba** [comment]
@dreadlokeur can you please post the log of the wallet? Write me on Telegram @davidbrm, so that I can assist you

**Comment by somdoron** [comment]
This is an obsolete project

**Comment by somdoron** [comment]
You probably want:

https://github.com/zenprotocol/zenwallet
